spring:
  flyway:
    enabled: true

app:
  auth:
    google:
      client-id: test-google-client-id.apps.googleusercontent.com

    jwt:
      issuer: memory-map-backend-test
      access-token-ttl: PT15M
      secret-base64: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
